### ISSUE TITLE
Migrating to agens-graph on my my nestjs app

### ISSUE THREAD

**Issue by avifatal** [liberation-data/drivine#103]
Hi,
I have a nestjs app with `redis-graph`.
Now,  Im migrating `redis-graph` to `agens graph`.
I have more then 100 queries, I want to avoid changing the cypher queries as much as possible.
How is that possible to force the driver to return labes, ids, and properties for all the querores? **without** changing all of my touching them?

In `redis-graph` when I return a node I get something like:
```json
{
    "id" : 1,
    "label" : "movies",
    "properties" : {
         "name": "Spiderman"
     } 
}
```
and the edge:
```json
{
   "id": 3,
   "from" : 1,
   "to": 5,
   "label" : "directedBy",
   "properties": {
      "score" : 5
    }
}
```

Can I shape the results to be like that without touching the queries?
Thanks

**Comment by jasperblues** [comment]
I'm not quite following your question. But before we get into that, did you know there's a version of Drivine that supports redisgraph? 

Its on a branch, because I haven't added transaction support (the Drivine @Transactional() decorator) but you might not need that. I could merge in now with those features throwing an "Not yet supported" error, if it helps? 

Now to your question. Do you want to query redisgraph to ask it what all of your labels are? Or export the whole graph? Or . . .

**Comment by avifatal** [comment]
Hi,
Thanks for the very quick answer.
We are leaving `redis-graph`, right now im POCing `agens-graph`.

`match(a:movies {name: 'Spiderman'}) return a` in redisgraph lib will return:
```
{
    "id" : 1,
    "label" : "movies",
    "properties" : {
         "name": "Spiderman"
     } 
}
```
As far as I remember from yesterday, your library return only the properties. How can I tweak your result to be like the json I put here.

Thanks

**Comment by jasperblues** [comment]
One way to do it: You can modify you query to something like 

```
match(a:movies {name: 'Spiderman'}) return {
  id: id(a), 
  label: labels(a), 
  properties: properties(a)
}
```

If you want to keep all of your original queries, perhaps you can create a method that transforms the original query into that format?

**Comment by jasperblues** [comment]
Welcome 👍
