### ISSUE TITLE
Website is down 

### ISSUE THREAD

**Issue by tgod009** [liberation-data/drivine#110]
[drivine.org](https://drivine.org/) gives a 404 error

**Comment by jasperblues** [comment]
Hey @tgod009 thanks for reporting!

https://www.linkedin.com/posts/jasper-blues-7781638_graphdatabase-opensource-apacheage-activity-7029627420315979776-BWzL?utm_source=share&utm_medium=member_desktop

^-- I decided to shut down liberation data as a for-profit company. 

It doesn't affect the open source stuff at all, except that instead of pay for website domains and etc I'm just going to host it here: https://liberation-data.github.io/drivine/
