### ISSUE TITLE
Transactional persistence manager is used when no @Transactional decorator is set when running concurrent queries

### ISSUE THREAD

**Issue by vongruenigen** [liberation-data/drivine#118]
Hey there :)

I think I've found another race condition when it comes to deciding which transaction manager should be used for a certain query.

In our project we're always using the `DelegatingPersistenceManager`. If possible we always run queries concurrently, and sometimes those concurrently running queries are wrapped with the `@Transactional` decorator, sometimes not. Until now this was no problem, but lately (after adding a new feature) we're running into `pushContext() must be called running a query` errors, without some obvious errors in our code.

I did some digging and I think I've found the issue: The problem is how it is decided which type of persistence manager the delegating persistence manager should delegate to (this is done here [DelegatingPersistenceManager.ts#L45](https://github.com/liberation-data/drivine/blob/master/src/manager/DelegatingPersistenceManager.ts#L45)). In certain cases it can happen that the transaction object is still set on the transaction context holder object, but transaction is already in the process of cleaning up everything (because the query wrapped in `@Transactional` is already completed and [`popContext`](https://github.com/liberation-data/drivine/blob/master/src/transaction/Transaction.ts#L74) already emptied the call stack). This then leads to the aforementioned error message for the query that was not decorated with `@Transactional`.

I've created a reproducible example in [this repository](https://github.com/vongruenigen/drivine-inspiration-transaction-release-issue) (when calling the `/routes/between/:start/:dest` endpoint with any params).

I'm not sure about the right approach to solve this, I basically see two ways:

1. Introduce some locking mechanism (e.g. mutex) to make sure either a query is run OR the transaction is released, but not both at the same time. This might lead to some weird edge cases though, for example when the transaction was marked to be rolled back. Because then the the non-transactional decorated query might be rolled back as well.
2. Somehow track if the current query (from the perspective of the delegating persistence manager) was wrapped with `@Transactional` higher up in the call chain (e.g. via continuation-local storage) and then decided which transaction manager to use based on that.

I think approach 2. would be the right way to go here, but I'm not entirely certain. That's why I'd like to hear your opinion, what do you think?

Thanks in advance!

**Comment by jasperblues** [comment]
Hey @vongruenigen 

Sorry for the late reply. Working on a production release with a client. 

If there's a call chain that is decorated as `@Transactional()` the transaction should only be completed/completing if: 

* Reached the outer-most part of the callchain (popContext in progress)
* An error was fired and the transaction is rolling back. 

Which case is it? Could it be the latter? 

> Somehow track if the current query (from the perspective of the delegating persistence manager) was wrapped with @Transactional higher up in the call chain (e.g. via continuation-local storage) and then decided which transaction manager to use based on that.

I believe this _is_ tracked, as you say, via continuation-local-storage.

**Comment by vongruenigen** [comment]
No worries, thanks for your reply. Regarding your question, it's the first case.

In our case it's the following situation: Imagine a single HTTP request reaches our backend. We then run different code paths concurrently (e.g. via multiple promises and `Promise.all`), where one of the code paths (let's call it `p1`) calls a service method decorated with `@Transactional`, and another without the decorator (called `p2`). The problem then arises if a certain race-condition is met, namely that `p2` executes a database query **while** the `TransactionalPersistenceManager` (used in `p1`) is in the process of cleaning up the transaction, but not yet finished (i.e. `TransactionContextHolder.transaction` is not yet set to `undefined`). This leads to the `TransactionalPersistenceManager` being used for queries in `p1` as well, even though no context was pushed to the stack.

**Comment by jasperblues** [comment]
OK, understood. 

I think the root of the issue is the following: 

## Currently 

* Continuation-local-storage creates a transactional context (storage bucket) per HTTP request. 
* This is intended (though not documented) to have transactions managed on that call-chain. 

## Meanwhile . . . 

Your HTTP endpoint fires off multiple promise call-chains that each have either transactional or non-transactional database work done on them. 

## Solution . .. 

Create a continuation-local-storage context _per_ promise chain. One for each. All should be well then. 

I'll check a bit later, but from memory `TransactionContextMiddleware` shows how to set up such a chain. There's also `InDrivineContext.run( () => aPromise)`. 

We should test and document how to do this easily.

**Comment by vongruenigen** [comment]
Sorry about the late reply, had a very hectic week.

Yes, this sounds like a plan. I'm not entirely sure if I understand you correctly, though: Are you proposing we wrap all those promise-chains *manually* in `InDrivineContext.run` in our codebase, or do you mean a solution where drivine manages this internally somehow?

**Comment by jasperblues** [comment]
Hey @vongruenigen 

Yes, Drivine is configurable, but the default behavior with a NestJS setup is that: 

* If a transaction is started on a http request and a new `@Transactional()` method is entered, it will participate in that currently running transaction, by design. 

If you require a new transaction per each of your promise chains, then it needs to be configured. There are two ways: 

* The first is the solution that I described above. Set up a new context per promise chain. 
* The next is to implement the `REQUIRES_NEW` propagation level here: https://github.com/liberation-data/drivine/blob/c0811c7257271d862dd9bc61b008d5b36922b893/src/transaction/Propagation.ts#L5

The above propagation level is not yet supported, but it should not be too hard to implement. Does that make sense?

**Comment by jasperblues** [comment]
NB, usage of the above propagation is intended to be: 

```@Transactional(propagation = Propagation.REQUIRES_NEW)```

**Comment by vongruenigen** [comment]
Thanks a lot @jasperblues, that sound like it could be a solution for our problem. I'm gonna try this as soon as I find some time, we're currently having a rather hectic time at work. Gonna let you know as soon as I've tried 👍

**Comment by jasperblues** [comment]
Possibly related: https://github.com/liberation-data/drivine/pull/122

Suggest to try 2.6.0

**Comment by vongruenigen** [comment]
Hey @jasperblues, thanks a lot for the notification!

We had a really bad times when it comes to workload the last two months, so I wasn't really able to look into this again (sorry about that). It seems that the problem is fixed with the MR you linked above, which I'm really glad about.

I think we can close this issue for now, if I still run into problems when trying out the new version I'll let you know by opening a new issue.

Thanks again, have a nice day :-)

**Comment by jasperblues** [comment]
Thanks @vongruenigen and especially thanks again to @alexgarbarev for the fix.
