### ISSUE TITLE
How to return IDs and Labels?

### ISSUE THREAD

**Issue by joeykilpatrick** [liberation-data/drivine#57]
Consider the following query:
```typescript
const movies = await this.persistenceManager.query<Movie>(
    new QuerySpecification<Movie>(`
        MATCH (m :Movie)
        RETURN m
    `)
);
```
There seems to be no way to get the ID or list of labels for each of the Movie nodes that the query will return. Instead, only the properties on the node can be retrieved. The following snippet of code is the relevant part of drivine that does this mapping:
```typescript
export class Neo4jResultMapper extends ResultMapper {

    ...

    toNative(val: any): any {
        if (val == undefined) {
            return val;
        }
        if (val instanceof neo4j.types.Node) {
            return this.toNative(val.properties);
        }
        if (val instanceof neo4j.types.Relationship) {
            return this.toNative(val.properties);
        }
        if (val instanceof neo4j.types.Point) {
            return val;
        }
        if (neo4j.isInt(val)) {
            return this.toNumberOrThrow(<Integer>val);
        }
        if (Array.isArray(val)) {
            return val.map((a) => this.toNative(a));
        }
        if (this.isRecord(val)) {
            return this.toNative(this.recordToNative(val));
        }
        if (typeof val === 'object') {
            return this.mapObj(this.toNative.bind(this), val);
        }
        return val;
    }

    ...

}
```
Perhaps it would be better to return the whole `neo4j.types.Node` instead of just the properties? If a user just wanted the properties without the Id and Labels, they could always just change the query to
```typescript
const movies = await this.persistenceManager.query<Movie>(
    new QuerySpecification<Movie>(`
        MATCH (m :Movie)
        RETURN PROPERTIES(m)
    `)
);
```

**Comment by jasperblues** [comment]
Hi @joeykilpatrick Thanks for reporting. 

Drivine has a default result mapper. Given the goal of creating a library that supports building graph-powered REST APIs and similar, the rationale  is to make 80% of cases as simple as possible and 20% possible. 

It is possible to do what you would like. Here are some options: 

## Return the Id and Label Properties from Query: 

```cypher
MATCH (actor:Person {name: $1})
WITH actor, [(actor)-[:ACTED_IN]-(movie:Movie) | movie {.title, .tagline, .released}] as movies
RETURN {
         id: id(actor),
         labels: labels(actor),
         actor:  actor,
         movies: movies
       }
```

## Plug in Your Own Result Mapper 

Rather than use the default result mapper you can plug in your own. Would you like to contribute an alternative mapper that: 

* Does what you want. 
* Users can specify as a config options when bootstrapping. 

Such a mapper could be Neo4j-specific if you wished, would not have to be general case for all supported graph DBs.

## Use Neo4j Driver directly. 

Another option is to use Neo4j driver directly. This would be a good idea if you prefer that format, and also don't wish to use other Drivine features like the transaction system, cursors, etc. 

----

I will leave this issue open in case you would like to pursue option #2 - Plug in your own mapper.

**Comment by jasperblues** [comment]
Closed for now @joeykilpatrick. Let me know if/when you would like to plug in a custom mapper, and we can help out.
