### ISSUE TITLE
[Docs] Show examples of unit testing with Drivine

### ISSUE THREAD

**Issue by NilsMoller** [liberation-data/drivine#96]
It would be great to have some documentation available to show how to *unit* test with Drivine.  The docs show how to perform end2end tests. It does not show how to get the injected `PersistenceManager` from the testing module, provide mock implementations, or spy on its methods.

An option would be to automatically mock the entire Drivine module: `jest.mock("@liberation-data/drivine")`, but this causes very vague errors regarding decorators.  

How would we go about this?

**Comment by jasperblues** [comment]
Here's what I do: 

* Using Drivine, build repositories that are injected into services. Mock the repositories, to test the services. 

* Add more integration tests to test the services with Drivine (hitting the database). Drivine provides a tool to run against real databsase (ie production snapshot) then rollback uncommitted transaction at the end of the test, leaving data in same initial test state for the next test. <-- Similar to eg Spring Boot. 


^-- Above is just one way as per own prefs. For the latter there are examples in the sample app, and some docs. (Let us know if anything not clear).

**Comment by NilsMoller** [comment]
What would these repositories look like? You would still have to test the repository itself, as it is part of your code base, and you'd end up with the same problem.

**Comment by jasperblues** [comment]
## Side Note On Naming

They are correctly called [Repositories](https://martinfowler.com/eaaCatalog/repository.html) (an older term is data access object) because this is a well known design pattern, presented in Eric Evans' book Domain Driven Design. They are responsible only for mediating between the database. 

### Key Benefits of the pattern are: 

* Encapsulate a set of reusable for shunting information to/from the data store. 
* Polymorphism: You can swap out one instance of the repository for another that does the same job. For example a test double (mock or stub) could be used in place. 

Meanwhile Services are for orchestrating business processes. In the [docs](https://drivine.org/) I show an example of a service that uses repos to orchestrate transfer of funds between accounts. 

## Addressing the Question

You can off course unit test these and/or provide a test double of repositories to services, to test services.  If you're a good person, you should. I don't provide an example in the docs/sources. If you face trouble achieving this with Drivine, we can address it. 

I'd be happy to take a PR to elaborate on unit testing, however key points are: 

* Since we're using dependency injection, just instantiate your class under test, providing a test double (ie mock) in place of the collaborator it would use normally.

**Comment by NilsMoller** [comment]
Testing the services isn't the problem. In that case, as you mentioned, you can mock the repository. I want to test the repository itself. For example, to ensure it makes the right database call given a certain input.

**Comment by jasperblues** [comment]
For repositories its the same approach. They need a `PersistenceManager`, so provide a test double in place of that `PersistenceManager`. There are no special utilities for this, at this time, sorry about that. If you were inclined to think that there should be, you'd be most welcome to fork the repo and add it.

**Comment by NilsMoller** [comment]
I tried mocking the whole Drivine module, but that results in some strange error about a decorator not being a function where the error points to one of the Drivine imports.  
I also tried spying on specifically the `PersistenceManager`, but it is an interface which can't be spied on (as far as I know).  
I also can't figure out how to extract the `PersistenceManager` out of the testing module (it's an interface, so `module.get<PersistenceManager>(PersistenceManager)` does not work). The `PersistenceManager` is also not injected through "regular" means, but using the `@InjectPersistenceManager` decorator.  

How would I provide a test double?

**Comment by jasperblues** [comment]
> Since we're using dependency injection, just instantiate your class under test, providing a test double (ie mock) in place of the collaborator it would use normally.

**Comment by NilsMoller** [comment]
With this, you mean actually instantiating the class using `new`? Wouldn't that go outside of Nest's `Test.createTestingModule`?

**Comment by jasperblues** [comment]
Welcome @NilsMoller !!! Thanks so much for collaborating. If you're using Neo4j, you might also want to check out the GraphQL integration. Shall we close this issue now?

**Comment by NilsMoller** [comment]
I did see their integration, but wrote it off as it did not fit in the existing solution. I think I will give it a second attempt once I find the time. Thank you again! I will close this now.

**Comment by jasperblues** [comment]
Yes it depends what you're looking for, but its very cool when it matches. 

I plan to add GraphQL features to Drivine in future. (Will work with any cypher compatible graphDB).
